spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/city_pass_db?allowPublicKeyRetrieval=true&useSSL=false
    username: ${user}
    password: ${pass}
